// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://irooiouqnjqcwtykwmyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyb29pb3VxbmpxY3d0eWt3bXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODczODAsImV4cCI6MjA3NTk2MzM4MH0.ecucbjaA6c5CN4EayO2M48PIqdc-Wl2v1Gn8Ktq2uQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);